EnableDefaultLinters: false

Require:
  - erblint-github

Linters:
  FinalNewline:
    Enabled: true

  TrailingWhitespace:
    Enabled: true

  ImageAlt:
    Enabled: true

  NoPositiveTabindex:
    Enabled: true


