EnableDefaultLinters: false

Require:
  - erblint-github

linters:
  FinalNewline:
    enabled: true

  TrailingWhitespace:
    enabled: true

  ImageAlt:
    enabled: true

  NoPositiveTabindex:
    enabled: true


